# Same as docker-compose file but no npm start command
version: "2"

services:

  app:
    image: dock-react-app
    environment:
        NODE_ENV: development
    ports:
        - "3000:3000"
    volumes:
        - ./app:/usr/src/app
